export const ADD_TO_CART = "ADD_TO_CART";
export const CHANGE_MESSAGE = "CHANGE_MESSAGE";
export const REMOVE_TO_CART = "REMOVE_TO_CART";
export const UPDATE_ADD_TO_CART = "UPDATE_ADD_TO_CART";
export const UPDATE_SUB_TO_CART = "UPDATE_SUB_TO_CART";